### ISSUE TITLE
[BUG] Tor instance fails to start

### ISSUE THREAD

**Issue by wigust** [bugfest/tor-controller#67]
**Describe the bug**
example-tor-instance-tor-daemon-9c8c48cbf-tnxm6 fails to start (following [Tor Instances](https://github.com/bugfest/tor-controller/tree/7a76239da6b04e29f0a444d333acfac614f601b6#tor-instances)).

**To Reproduce**
Install tor-controller Helm chart version 0.1.14.

Create Tor object:
```
apiVersion: tor.k8s.torproject.org/v1alpha2
kind: Tor
metadata:
  name: example-tor-instance
  namespace: tor-controller-instance
```

You will get a pod like example-tor-instance-tor-daemon-9c8c48cbf-tnxm6 which fails to start because of the error:
```
Message: failed to create containerd task: failed to create shim task: OCI
runtime create failed: runc create failed: unable to start container process:
error during container init: error mounting
"/var/lib/containerd/io.containerd.grpc.v1.cri/containers/17ea4614b07d137e2e46fe9ead37e639c2bfe7b5c89b6040705b4821f8865044/volumes/0b41a74427d7e4c3db972fb4b3aed48e731b38018f0e6e8411d28c7ba481d3fb"
to rootfs at "/run/tor/service": mkdir
/run/containerd/io.containerd.runtime.v2.task/k8s.io/17ea4614b07d137e2e46fe9ead37e639c2bfe7b5c89b6040705b4821f8865044/rootfs/run/tor/service:
read-only file system: unknown
```

**Expected behavior**
Pod in a Running state.

**Additional information**
A workaround to start Tor is:

Stop the controller:
```kubectl -n tor-controller scale --replicas 0 deployments.apps tor-controller```

Add DataDirectory to Tor config:
```kubectl -n tor-controller-instance edit configmaps example-tor-instance-tor-config```
```DataDirectory /var/lib/tor```

Add mounts:
```kubectl` -n tor-controller-instance edit deployments.apps example-tor-instance-tor-daemon```
```
        volumeMounts:
        - mountPath: /run/tor/service
          name: run-tor-service
        - mountPath: /var/lib/tor
          name: var-lib-tor
     ...
     volumes:
      - emptyDir: {}
        name: run-tor-service
      - hostPath:
          path: /var/lib/tor-controller-instance
          type: Directory
        name: var-lib-tor
```

**System (please complete the following information):**
 - Platform: Linux 5.13.16 x86_64
 - Kubelet version: 1.25.4
