### ISSUE TITLE
[REQUEST] enable control port access (already possible?)

### ISSUE THREAD

**Issue by coffeel0ver** [bugfest/tor-controller#76]
First of all thank you @bugfest for this repo.

I would like to use the control port on an OnionService to be able to kill specific onion curcuits to prevent flooding attacks.
I haven't found a way to enable control port for an OnionService/OnionBalancedService in the documentation.
Is there a way to to enable it and allow connection from other apps inside the cluster?

If not, could you please add this feature? It won't break any of the functions itself from my point of view.

Is there a donations page for this project?

Thanks in advance!

**Comment by bugfest** [comment]
Hi @coffeel0ver, thanks for your kind words. 

> I would like to use the control port on an OnionService to be able to kill specific onion curcuits to prevent flooding attacks. I haven't found a way to enable control port for an OnionService/OnionBalancedService in the documentation. Is there a way to to enable it and allow connection from other apps inside the cluster?
> 
> If not, could you please add this feature? It won't break any of the functions itself from my point of view.

I already developed `spec.control.enable` for the Tor instances but this feature hasn't been ported yet to the OnionService/OnionBalancedService: https://github.com/bugfest/tor-controller/blob/f60092be56eeaf5eb033fc3d2fac2e3d53eadf80/controllers/tor/tor_configmap.go#L74-L82

You can enable Tor's control port in OnionService and OnionBalancedService using the [extraConfig attribute](https://github.com/bugfest/tor-controller/tree/f60092be56eeaf5eb033fc3d2fac2e3d53eadf80?tab=readme-ov-file#custom-settings-for-tor-daemon).

Examples:

```yaml
# OnionService
apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: onionservice-controlport-enabled
spec:
  version: 3
  rules: [...]
  extraConfig: |
    ControlPort 0.0.0.0:9051
    HashedControlPassword yourhashedpasswordhere
```

```yaml
# OnionBalancedService
apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionBalancedService
metadata:
  name: onionbalancedservice-controlport-enabled
spec:
  backends: 3
  template:
    spec:
      version: 3
      rules: [...]
      extraConfig: |
        ControlPort 0.0.0.0:9051
        HashedControlPassword yourhashedpasswordhere
```

> Is there a donations page for this project?

I currently don't take donations for any of my projects. But if you still do want to contribute you can donate to Tor project instead https://donate.torproject.org so that all of us can keep using Tor network : ) 

Regards,
BF

**Comment by coffeel0ver** [comment]
Hey @bugfest  let me explain the problem a bit more in detail:

As you are using the following definition for the OnionService:

```
apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: myapp-onion-service
  namespace: tor-proxy
spec:
  version: 3
  rules:
    - port:
        name: myapp
        number: 80
      backend:
        service:
          name: traefik
          port:
            number: 80
  extraConfig: |
    ControlPort 9051
    HashedControlPassword XXXXXXXXX
```

tor is returning this error:

```
2024-04-04T22:17:56.585543697+02:00 Apr 04 20:17:56.585 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
2024-04-04T22:17:56.585549196+02:00 Apr 04 20:17:56.585 [notice] Read configuration file "/run/tor/torfile".
Apr 04 20:17:56.586 [warn] You specified a nonzero ControlPort along with 'ControlPort 0' in the same configuration. Did you mean to disable ControlPort or not?
2024-04-04T22:17:56.586432710+02:00 Apr 04 20:17:56.586 [warn] Failed to parse/validate config: Invalid ControlPort configuration
Apr 04 20:17:56.586 [err] Reading config failed--see warnings above.
time="2024-04-04T20:17:56Z" level=info msg="exit status 1"
```

With the current torfile it is not possible to set a ControlPort via extraConfig option in the yaml, since the torfile already contains ControlPort 0 before the extraConfig is appended.

Could you please edit the torfile and remove the ControlPort from this file? ControlPort should be disabled by tor by default (no need to explicitly define it in the torfile). Aside from that it's not exposed, without a service anyways.

Could you please make this small edit, otherwise it won't be able to use the `ControlPort`.
Thank you in advance!
